# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Get posts

on:
    push:
        branches: ["master"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Create env file
              id: env
              run: |
                  touch .env
                  echo NOTION_SECRET = ${{ secrets.NOTION_SECRET }} >> .env
                  echo NOTION_DATABASE = d3093d5c8d0c499ea68785f14409b144 >> .env
                  cat .env
            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "20.x"
                  cache: "yarn"
            - name: Install deps
              run: yarn install
            - name: Run script
              if: steps.env.outcome == 'success'
              env:
                NOTION_SECRET: ${{ secrets.NOTION_SECRET }}
                NOTION_DATABASE: d3093d5c8d0c499ea68785f14409b144
              run: yarn start
